Insert Into Media_People ([Name]) Values ('Chris Hayes')
Insert Into Show ([Host],Network,[Show]) Values ('Chris Hayes','MSNBC','All In')
Insert Into Media_People ([Name]) Values ('Chris Matthews')
Insert Into Show ([Host],Network,[Show]) Values ('Chris Matthews','MSNBC','Hardball')
Insert Into Media_People ([Name]) Values ('Rachel Maddow')
Insert Into Show ([Host],Network,[Show]) Values ('Rachel Maddow','MSNBC','Rachel Maddow Show')
Insert Into Media_People ([Name]) Values ('Lawrence O`Donnell')
Insert Into Show ([Host],Network,[Show]) Values ('Lawrence O`Donnell','MSNBC','The Last Word')
Insert Into Media_People ([Name]) Values ('Brian Williams')
Insert Into Show ([Host],Network,[Show]) Values ('Brian Williams','MSNBC','The 11th Hour with Brian Williams')
